# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


User.create(fname:'Alex',lname:'Anderson',email:'aa.a@ufl.edu',password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Bob',lname:'Benhur',email:'bb.b@ufl.edu',password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Calvin',lname:'Clien',email:'cc.c@ufl.edu',password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Dan',lname:'Duran',email:'dd.d@ufl.edu',password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Edgar',lname:'Edgarson',email:'ee.e@ufl.edu',password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Fredrick',lname:'Fredrickson',email:'ff.f@ufl.edu',password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Gunther',lname:'Gaterson',email:'gg.g@ufl.edu',password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Howard',lname:'Hughes',email:'hh.h@ufl.edu',password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Ignor',lname:'Ivanovich',email:'ii.i@ufl.edu',password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Johnny',lname:'Joker',email:'jj.j@ufl.edu',password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Kurt',lname:'Kobain',email:'kk.k@ufl.edu',password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Lars',lname:'Lindsor',email:'ll.l@ufl.edu',password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Mega',lname:'Man',email:'mm.m@ufl.edu',password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Nitro',lname:'Nox',email:'nn.n@ufl.edu',password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Oowich',lname:'Olrich',email:'oo.o@ufl.edu',password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Peter',lname:'Parkinson',email:'pp.p@ufl.edu',password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Quinn',lname:'Quarterly',email:'qq.q@ufl.edu',password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Road',lname:'Runner',email:'rr.r@ufl.edu',password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Saucy',lname:'Sachharrine',email:'ss.s@ufl.edu',password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Titty',lname:'Twister',email:'tt.t@ufl.edu',password:'topsecret',password_confirmation:'topsecret')

Competition.create(name:'Pancake Optimization',created_at:Time.now)
Competition.create(name:'Rooster Chasing',created_at:Time.now)
Competition.create(name:'Bridge Demolition',created_at:Time.now)
Competition.create(name:'LSD Legalization',created_at:Time.now)
Competition.create(name:'Cocaine Snorting',created_at:Time.now)
Competition.create(name:'Poop Masters',created_at:Time.now)
Competition.create(name:'The Seventh Reich',created_at:Time.now)
Competition.create(name:'Project Jupiter',created_at:Time.now)
Competition.create(name:'The Cactus Incident',created_at:Time.now)
Competition.create(name:'Operation Pteradactyl',created_at:Time.now)
Competition.create(name:'Bullet Proof Spoons',created_at:Time.now)

Skill.create(name:'Data Visualization',category:'Excel',weight:5,created_at:Time.now)
Skill.create(name:'Formulae Familiarity',category:'Excel',weight:5,created_at:Time.now)
Skill.create(name:'Pivot Tables',category:'Excel',weight:5,created_at:Time.now)
Skill.create(name:'Financial Modeling',category:'Finance',weight:5,created_at:Time.now)
Skill.create(name:'Image Processing',category:'Graphical Design',weight:5,created_at:Time.now)
Skill.create(name:'Posters',category:'Graphical Design',weight:5,created_at:Time.now)
Skill.create(name:'Video Production',category:'Graphical Design',weight:5,created_at:Time.now)
Skill.create(name:'Audience Empathy',category:'Narration',weight:5,created_at:Time.now)
Skill.create(name:'Logical Flow',category:'Narration',weight:5,created_at:Time.now)
Skill.create(name:'Clean Formatting',category:'Powerpoint',weight:5,created_at:Time.now)
Skill.create(name:'Transitions',category:'Powerpoint',weight:5,created_at:Time.now)
Skill.create(name:'Visuals',category:'Powerpoint',weight:5,created_at:Time.now)
Skill.create(name:'Gestures',category:'Public Speaking',weight:5,created_at:Time.now)
Skill.create(name:'Space Usage',category:'Public Speaking',weight:5,created_at:Time.now)
Skill.create(name:'Volume',category:'Public Speaking',weight:5,created_at:Time.now)
Skill.create(name:'Academic Journals',category:'Research',weight:5,created_at:Time.now)
Skill.create(name:'News Papers',category:'Research',weight:5,created_at:Time.now)
Skill.create(name:'Online Websites',category:'Research',weight:5,created_at:Time.now)

