# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


User.create(fname:'Alex',lname:'Ajackson',email:'aa.a@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Bhumika',lname:'Borealis',email:'bb.b@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Celsus',lname:'Celvin',email:'cc.c@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Dan',lname:'Duran',email:'dd.d@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Edgar',lname:'Edgarson',email:'ee.e@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Fredrick',lname:'Fredrickson',email:'ff.f@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Gunther',lname:'Williams',email:'gg.g@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Howard',lname:'Howareyou',email:'hh.h@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Ignor',lname:'Ivrivon',email:'ii.i@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Johnny',lname:'Joker',email:'jj.j@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Kurt',lname:'Kobain',email:'kk.k@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Lars',lname:'Loginson',email:'ll.l@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Mega',lname:'Man',email:'mm.m@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Nitro',lname:'Nox',email:'nn.n@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Oowich',lname:'Olrich',email:'oo.o@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Peter',lname:'Parkinson',email:'pp.p@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Quinn',lname:'Quarterly',email:'qq.q@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Road',lname:'Runner',email:'rr.r@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Saucy',lname:'Sachharrine',email:'ss.s@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Tryptam',lname:'Tyme',email:'tt.t@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')

User.create(fname:'Allen',lname:'Armour',email:'aa@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Bradley',lname:'Barns',email:'bb@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Chris',lname:'Hardwick',email:'ch@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Danica',lname:'Patricks',email:'dp.d@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Edward',lname:'Cullen',email:'ec.e@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Fred',lname:'Sampson',email:'fs@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Gunner',lname:'Gat',email:'gg@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Howard',lname:'Hewitt',email:'hh@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Igor',lname:'Ikly',email:'ii@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Johnny',lname:'Rocket',email:'jr@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Kurt',lname:'Russell',email:'kr@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Lars',lname:'Rodriguez',email:'lr@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Mega',lname:'Mann',email:'mm@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Nitro',lname:'Glycerin',email:'ng@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Owen',lname:'Wilson',email:'ow@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Peter',lname:'Parker',email:'pp@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Quinn',lname:'Lane',email:'ql@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Road',lname:'Acme',email:'ra@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Saucy',lname:'Sanders',email:'ss@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Tammy',lname:'Baker',email:'tb@ufl.edu',graduation:(Time.now.year+rand(0..3)),password:'topsecret',password_confirmation:'topsecret')

Skill.create(name:'Basic Excel',category:'Excel',weight:2,created_at:Time.now)
Skill.create(name:'Data Visualization',category:'Excel',weight:4,created_at:Time.now)
Skill.create(name:'Pivot Tables',category:'Excel',weight:4,created_at:Time.now)
Skill.create(name:'Basic FM',category:'Financial Modelling',weight:1,created_at:Time.now)
Skill.create(name:'Constraints Modelling',category:'Financial Modelling',weight:3,created_at:Time.now)
Skill.create(name:'Forecasting',category:'Financial Modelling',weight:2,created_at:Time.now)
Skill.create(name:'After Effects',category:'Graphic Design',weight:1,created_at:Time.now)
Skill.create(name:'Photoshop',category:'Graphic Design',weight:5,created_at:Time.now)
Skill.create(name:'Audience Empathy',category:'Narration',weight:2,created_at:Time.now)
Skill.create(name:'Story Clarity',category:'Narration',weight:5,created_at:Time.now)
Skill.create(name:'Story Flow',category:'Narration',weight:2,created_at:Time.now)
Skill.create(name:'Slide Animations',category:'Powerpoint',weight:4,created_at:Time.now)
Skill.create(name:'Slide Formatting',category:'Powerpoint',weight:4,created_at:Time.now)
Skill.create(name:'Public Speaking',category:'Public Speaking',weight:1,created_at:Time.now)
Skill.create(name:'Online Media',category:'Research',weight:1,created_at:Time.now)
Skill.create(name:'Doc. Standards',category:'Research',weight:2,created_at:Time.now)


Program.create(name:'EMBA',description:'Executive MBA',created_at:Time.now)
Program.create(name:'FTMBAA',description:'Full-Time MBA All Majors',created_at:Time.now)
Program.create(name:'FTMBAB',description:'Full-Time MBA Business Majors',created_at:Time.now)
Program.create(name:'OMBA',description:'Online MBA',created_at:Time.now)
Program.create(name:'PMBA',description:'Professional MBA',created_at:Time.now)
Program.create(name:'SFMBA',description:'South Florida MBA',created_at:Time.now)
Program.create(name:'ISOM',description:'Information Systems / Operations Management',created_at:Time.now)
Program.create(name:'MAcc',description:'Masters Accounting',created_at:Time.now)
Program.create(name:'MIB',description:'Masters International Business',created_at:Time.now)
Program.create(name:'MSE',description:'Masters Entrepreneurship',created_at:Time.now)
Program.create(name:'MSF',description:'Masters Finance',created_at:Time.now)
Program.create(name:'MSRE',description:'Masters Real Estate',created_at:Time.now)
Program.create(name:'MSM',description:'Masters Management',created_at:Time.now)
