# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


User.create(fname:'Alex',lname:'Ajackson',email:'aa.a@ufl.edu',program:'MAcc',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Bhumika',lname:'Borealis',email:'bb.b@ufl.edu',program:'EMBA',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Celsus',lname:'Celvin',email:'cc.c@ufl.edu',program:'OMBA',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Dan',lname:'Duran',email:'dd.d@ufl.edu',program:'MIM',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Edgar',lname:'Edgarson',email:'ee.e@ufl.edu',program:'EMBA',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Fredrick',lname:'Fredrickson',email:'ff.f@ufl.edu',program:'MAcc',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Gunther',lname:'Williams',email:'gg.g@ufl.edu',program:'MSE',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Howard',lname:'Howareyou',email:'hh.h@ufl.edu',program:'OMBA',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Ignor',lname:'Ivrivon',email:'ii.i@ufl.edu',program:'PMBA',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Johnny',lname:'Joker',email:'jj.j@ufl.edu',program:'MIM',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Kurt',lname:'Kobain',email:'kk.k@ufl.edu',program:'ISOM',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Lars',lname:'Loginson',email:'ll.l@ufl.edu',program:'MAcc',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Mega',lname:'Man',email:'mm.m@ufl.edu',program:'ISOM',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Nitro',lname:'Nox',email:'nn.n@ufl.edu',program:'MIM',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Oowich',lname:'Olrich',email:'oo.o@ufl.edu',program:'FTMBA',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Peter',lname:'Parkinson',email:'pp.p@ufl.edu',program:'MSE',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Quinn',lname:'Quarterly',email:'qq.q@ufl.edu',program:'MSF',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Road',lname:'Runner',email:'rr.r@ufl.edu',program:'MAcc',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Saucy',lname:'Sachharrine',email:'ss.s@ufl.edu',program:'EMBA',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Tryptam',lname:'Tyme',email:'tt.t@ufl.edu',program:'FTMBA',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')

User.create(fname:'Allen',lname:'Armour',email:'aa@ufl.edu',program:'EMBA',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Bradley',lname:'Barns',email:'bb@ufl.edu',program:'FTMBA',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Chris',lname:'Hardwick',email:'ch@ufl.edu',program:'FTMBA',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Danica',lname:'Patricks',email:'dp.d@ufl.edu',program:'PMBA',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Edward',lname:'Cullen',email:'ec.e@ufl.edu',program:'PMBA',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Fred',lname:'Sampson',email:'fs@ufl.edu',program:'OMBA',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Gunner',lname:'Gat',email:'gg@ufl.edu',program:'PMBA',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Howard',lname:'Hewitt',email:'hh@ufl.edu',program:'OMBA',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Igor',lname:'Ikly',email:'ii@ufl.edu',program:'SFMBA',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Johnny',lname:'Rocket',email:'jr@ufl.edu',program:'MSRE',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Kurt',lname:'Russell',email:'kr@ufl.edu',program:'MSRE',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Lars',lname:'Rodriguez',email:'lr@ufl.edu',program:'MSM',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Mega',lname:'Mann',email:'mm@ufl.edu',program:'MSF',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Nitro',lname:'Glycerin',email:'ng@ufl.edu',program:'MSM',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Owen',lname:'Wilson',email:'ow@ufl.edu',program:'ISOM',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Peter',lname:'Parker',email:'pp@ufl.edu',program:'SFMBA',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Quinn',lname:'Lane',email:'ql@ufl.edu',program:'SFMBA',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Road',lname:'Acme',email:'ra@ufl.edu',program:'MSF',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Saucy',lname:'Sanders',email:'ss@ufl.edu',program:'MIB',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')
User.create(fname:'Tammy',lname:'Baker',email:'tb@ufl.edu',program:'MSM',graduation:(Time.now+rand(0..3).years),password:'topsecret',password_confirmation:'topsecret')

Competition.create(name:'Pancake Optimization',start:(Time.now+rand(0..4).months),comp_type:'24-Hour',creator_id:rand(1..40),created_at:Time.now)
Competition.create(name:'Rooster Chasing',start:(Time.now+rand(0..4).months),comp_type:'24-Hour',creator_id:rand(1..40),created_at:Time.now)
Competition.create(name:'Bridge Demolition',start:(Time.now+rand(0..4).months),comp_type:'Standard',creator_id:rand(1..40),created_at:Time.now)
Competition.create(name:'Watching Paint Dry',start:(Time.now+rand(0..4).months),comp_type:'24-Hour',creator_id:rand(1..40),created_at:Time.now)
Competition.create(name:'The Ernshaw Principle',start:(Time.now+rand(0..4).months),comp_type:'Standard',creator_id:rand(1..40),created_at:Time.now)
Competition.create(name:'Poop Masters',start:(Time.now+rand(0..4).months),comp_type:'Standard',creator_id:rand(1..40),created_at:Time.now)
Competition.create(name:'The Seventh Reich',start:(Time.now+rand(0..4).months),comp_type:'24-Hour',creator_id:rand(1..40),created_at:Time.now)
Competition.create(name:'Project Jupiter',start:(Time.now+rand(0..4).months),comp_type:'24-Hour',creator_id:rand(1..40),created_at:Time.now)
Competition.create(name:'The Cactus Incident',start:(Time.now+rand(0..4).months),comp_type:'Standard',creator_id:rand(1..40),created_at:Time.now)
Competition.create(name:'Operation Pteradactyl',start:(Time.now+rand(0..4).months),comp_type:'24-Hour',creator_id:rand(1..40),created_at:Time.now)
Competition.create(name:'Bullet Proof Spoons',start:(Time.now+rand(0..4).months),comp_type:'24-Hour',creator_id:rand(1..40),created_at:Time.now)
Competition.create(name:'The Grandfather Paradox',start:(Time.now+rand(0..4).months),comp_type:'Standard',creator_id:rand(1..40),created_at:Time.now)

Skill.create(name:'Data Visualization',category:'Excel',weight:rand(1..5),created_at:Time.now)
Skill.create(name:'Formulae Familiarity',category:'Excel',weight:rand(1..5),created_at:Time.now)
Skill.create(name:'Pivot Tables',category:'Excel',weight:rand(1..5),created_at:Time.now)
Skill.create(name:'Financial Modeling',category:'Finance',weight:rand(1..5),created_at:Time.now)
Skill.create(name:'Image Processing',category:'Graphical Design',weight:rand(1..5),created_at:Time.now)
Skill.create(name:'Posters',category:'Graphical Design',weight:rand(1..5),created_at:Time.now)
Skill.create(name:'Video Production',category:'Graphical Design',weight:rand(1..5),created_at:Time.now)
Skill.create(name:'Audience Empathy',category:'Narration',weight:rand(1..5),created_at:Time.now)
Skill.create(name:'Logical Flow',category:'Narration',weight:rand(1..5),created_at:Time.now)
Skill.create(name:'Clean Formatting',category:'Powerpoint',weight:rand(1..5),created_at:Time.now)
Skill.create(name:'Transitions',category:'Powerpoint',weight:rand(1..5),created_at:Time.now)
Skill.create(name:'Visuals',category:'Powerpoint',weight:rand(1..5),created_at:Time.now)
Skill.create(name:'Gestures',category:'Public Speaking',weight:rand(1..5),created_at:Time.now)
Skill.create(name:'Space Usage',category:'Public Speaking',weight:rand(1..5),created_at:Time.now)
Skill.create(name:'Volume',category:'Public Speaking',weight:rand(1..5),created_at:Time.now)
Skill.create(name:'Academic Journals',category:'Research',weight:rand(1..5),created_at:Time.now)
Skill.create(name:'News Papers',category:'Research',weight:rand(1..5),created_at:Time.now)
Skill.create(name:'Online Websites',category:'Research',weight:rand(1..5),created_at:Time.now)

UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)

UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)

UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)

UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)

UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)

UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)

UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)
UserSkill.create(user_id:rand(1..40),skill_id:rand(1..18),level:rand(1..5),created_at:Time.now)